remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- name: Markdown-HTML
  uses: ZacJW/markdown-html-action@1.2.0
  with:
          input_files: '[["*.md"], ["dir1/*.md", "dir2/*.md]]'
          output_files: '["out1.html", "out2.html"]'
  packages: 'pymdown-extensions'
  extensions: '["pymdownx.extra"]'
            
