name: deploy-github-pages
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: deploy
        uses: ZacJW/markdown-html-action@1.1.0
        with:
          input_files: '[["*.md"]]'
          output_files: '["build/index.html"]'
          packages: 'pymdown-extensions'
          extensions: '["pymdownx.extra"]'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
