name: deploy-github-pages

# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Convert Markdown to Pages
        uses: wranders/markdown-to-pages-action@v0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pages
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.build.outputs.artifacts.pages }}

    steps:
      - name: Download Pages Artifact
        uses: actions/download-artifact@v2
        with:
          name: pages
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
