name: Generate Chirpy Posts from LeetSync

on:
  push:
    branches:
      - main

jobs:
  generate-posts:
    if: ${{ contains(github.event.head_commit.message, 'LeetSync') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LeetSync repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run LeetSync → Chirpy script
        run: |
          python migrate.py

      - name: Clone anurag252.github.io repository
        run: |
          git clone https://Anurag252:${{ secrets.GH_PAGES_TOKEN }}@github.com/Anurag252/anurag252.github.io.git ../anurag252.github.io

      - name: Copy new posts into GitHub Pages repo
        run: |
          mkdir -p ../anurag252.github.io/_posts
          for file in chirpy/*; do
            target="../anurag252.github.io/_posts/$(basename "$file")"
            if [ ! -f "$target" ]; then
              cp "$file" "$target"
              echo "Copied: $(basename "$file")"
            else
              echo "Skipped (already exists): $(basename "$file")"
            fi
          done

      - name: Commit and push to GitHub Pages repo
        run: |
          cd ../anurag252.github.io
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts
          git commit -m "Auto-generate Chirpy posts from LeetSync" || echo "No changes to commit"
          git push
